global:
  resolve_timeout: 1m

route:
  receiver: "telegram"
  group_by: ["alertname", "job"]
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: "telegram"
    webhook_configs:
      - url: "http://alertgram:8080/alerts"
        send_resolved: true
